apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: castai-agent

bases:
  - ../../base

configMapGenerator:
  - name: castai-cluster-config
    literals:
      - ENVIRONMENT=production
      - CLUSTER_NAME=production-eks-cluster

patchesStrategicMerge:
  - values/cluster-agent-values.yaml