# CAST AI Node Template: hyperscale_spot 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monarch-accumall
  namespace: default
  labels:
    app: monarch
    workload: accumall
spec:
  replicas: 0
  selector:
    matchLabels:
      app: monarch-accumall
  template:
    metadata:
      labels:
        app: monarch-accumall
        spark-nodeselect-instance-type: amd64-64-16
        spark-nodeselect-nodepool-group: hyper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  spark-nodeselect-nodepool-group: hyper
              topologyKey: kubernetes.io/hostname
      containers:
      - name: monarch-accumall
        image: nginx:latest
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
            ephemeral-storage: "16Mi"
      nodeSelector:
        spark-nodeselect-instance-type: amd64-64-16
        spark-nodeselect-nodepool-group: hyper
        spark-nodeselect-preemptible: "true"
      terminationGracePeriodSeconds: 10
