# CAST AI Node Template: hyperscale_spot 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monarch-accumall
  namespace: default
  labels:
    app: monarch
    workload: accumall
spec:
  replicas: 0
  selector:
    matchLabels:
      app: monarch-accumall
  template:
    metadata:
      labels:
        app: monarch-accumall
        spark-nodeselect-instance-type: amd64-64-16
        spark-nodeselect-nodepool-group: hyper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  spark-nodeselect-nodepool-group: hyper
              topologyKey: kubernetes.io/hostname
      containers:
      - name: monarch-accumall
        image: public.ecr.aws/docker/library/busybox:stable
        command: ["/bin/sh", "-c"]
        args:
          - |
            counter=0
            while true; do
              echo "Counter: $counter"
              counter=$((counter + 1))
              sleep 1
            done
        resources:
          requests:
            cpu: "2"
            memory: "4Gi"
            ephemeral-storage: "16Mi"
      nodeSelector:
        workload: monarch-accumall
        spark-nodeselect-instance-type: amd64-64-16
        spark-nodeselect-nodepool-group: hyper
        spark-nodeselect-preemptible: "true"
      terminationGracePeriodSeconds: 10
