# CAST AI Node Template: hyperscale_spot 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monarch-mig
  namespace: default
  labels:
    app: monarch
    workload: mig
spec:
  replicas: 0
  selector:
    matchLabels:
      app: monarch-mig
  template:
    metadata:
      labels:
        app: monarch-mig
        spark-nodeselect-instance-type: amd64-64-16
        spark-nodeselect-nodepool-group: hyper
    spec:
      containers:
      - name: monarch-mig
        image: nginx:latest
        resources:
          requests:
            cpu: "4"
            memory: "8Gi"
            ephemeral-storage: "32Mi"
      nodeSelector:
        spark-nodeselect-instance-type: amd64-64-16
        spark-nodeselect-nodepool-group: hyper
        spark-nodeselect-preemptible: "true"
      terminationGracePeriodSeconds: 10
