# CAST AI Node Template: hyperscale_spot
apiVersion: apps/v1
kind: Deployment
metadata:
  name: monarch-prep
  namespace: default
  labels:
    app: monarch
    workload: prep
spec:
  replicas: 0
  selector:
    matchLabels:
      app: monarch-prep
  template:
    metadata:
      labels:
        app: monarch-prep
        spark-nodeselect-instance-type: amd64-64-16
        spark-nodeselect-nodepool-group: hyper
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  spark-nodeselect-nodepool-group: hyper
              topologyKey: kubernetes.io/hostname
      containers:
      - name: monarch-prep
        image: nginx:latest
        resources:
          requests:
            cpu: "1"
            memory: "2Gi"
            ephemeral-storage: "8Mi"
      nodeSelector:
        spark-nodeselect-instance-type: amd64-64-16
        spark-nodeselect-nodepool-group: hyper
        spark-nodeselect-preemptible: "true"
      terminationGracePeriodSeconds: 10
